schema: olm.composite.catalogs
catalogs:
  - name: "4.13"
    destination:
      baseImage: quay.io/operator-framework/opm:v1.26
      workingDir: .
    builders:
      - olm.builder.basic
  - name: "4.12"
    destination:
      baseImage: quay.io/operator-framework/opm:v1.26
      workingDir: .
    builders:
      - olm.builder.basic
